name: iea_scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - argon2-cffi=21.1.0
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.10.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bs4=4.10.0
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.9
  - colorama=0.4.4
  - cramjam=2.5.0
  - cryptography=36.0.0
  - cssselect=1.1.0
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fake-useragent=0.1.11
  - fastparquet=0.7.2
  - fsspec=2021.11.1
  - greenlet=1.1.2
  - h11=0.12.0
  - html5lib=1.1
  - icu=68.2
  - idna=3.1
  - importlib-metadata=4.8.2
  - importlib_resources=5.4.0
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.30.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - jsonschema=4.2.1
  - jupyter=1.0.0
  - jupyter_client=7.1.0
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.11
  - lxml=4.7.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.3
  - matplotlib=3.5.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - more-itertools=8.12.0
  - msys2-conda-epoch=20160418
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.4
  - notebook=6.4.6
  - numpy=1.21.4
  - odfpy=1.4.1
  - openpyxl=3.0.9
  - openssl=1.1.1m
  - outcome=1.1.0
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - parse=1.19.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=21.3.1
  - pluggy=1.0.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - prompt_toolkit=3.0.24
  - py=1.11.0
  - pycountry=20.7.3
  - pycparser=2.21
  - pyee=8.1.0
  - pygments=2.10.0
  - pyodbc=4.0.32
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyppeteer=0.2.6
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyquery=1.4.3
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-snappy=0.6.0
  - python_abi=3.9
  - pytz=2021.3
  - pywin32=302
  - pywinpty=1.1.6
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=1.11.3
  - requests=2.26.0
  - requests-html=0.10.0
  - retry=0.9.2
  - selenium=4.1.0
  - send2trash=1.8.0
  - setuptools=59.6.0
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.5.0
  - sqlalchemy=1.4.28
  - sqlite=3.37.0
  - tbb=2021.4.0
  - terminado=0.12.1
  - testpath=0.5.0
  - thrift=0.15.0
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - trio=0.20.0
  - trio-websocket=0.9.2
  - tzdata=2021e
  - ucrt=10.0.20348.0
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - w3lib=1.22.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websockets=9.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wsproto=1.1.0
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - pip:
    - anyio==3.5.0
    - blinker==1.4
    - brotli==1.0.9
    - bs4==0.0.1
    - chardet==3.0.4
    - datetime==4.4
    - deprecation==2.1.0
    - eikon==1.1.14
    - h2==3.2.0
    - hpack==3.0.0
    - httpcore==0.14.7
    - httpx==0.22.0
    - hyperframe==5.2.0
    - idna==2.10
    - incapsula-cracker-py3==0.1.8.1
    - kaitaistruct==0.9
    - pyasn1==0.4.8
    - pydivert==2.1.0
    - rfc3986==1.5.0
    - selenium-wire==4.6.3
    - sphinx-rtd-theme
    - websocket-client==1.3.1
    - zope-interface==5.4.0
    - zstandard==0.17.0


