/****** Object:  Table [main].[ice_futures_options_data]    Script Date: 23-03-2021 20:47:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [main].[futures_options_data]
GO

CREATE TABLE [main].[futures_options_data](
	[Market_and_Exchange_Names] [varchar](100) NULL,
	[As_of_Date_In_Form_YYMMDD] [varchar](6) NOT NULL,
	[Report_Date_as_YYYY-MM-DD] [varchar](10) NULL,
	[As_of_Date_Form_MM/DD/YYYY] [varchar](10) NULL,
	[CFTC_Contract_Market_Code] [varchar](10) NOT NULL,
	[CFTC_Market_Code] [varchar](4) NOT NULL,
	[CFTC_Region_Code] [int] NOT NULL,
	[CFTC_Commodity_Code] [varchar](10) NOT NULL,
	[Open_Interest_All] [float] NULL,
	[Prod_Merc_Positions_Long_All] [int] NULL,
	[Prod_Merc_Positions_Short_All] [int] NULL,
	[Swap_Positions_Long_All] [int] NULL,
	[Swap_Positions_Short_All] [int] NULL,
	[Swap_Positions_Spread_All] [int] NULL,
	[M_Money_Positions_Long_All] [int] NULL,
	[M_Money_Positions_Short_All] [int] NULL,
	[M_Money_Positions_Spread_All] [int] NULL,
	[Other_Rept_Positions_Long_All] [int] NULL,
	[Other_Rept_Positions_Short_All] [int] NULL,
	[Other_Rept_Positions_Spread_All] [int] NULL,
	[Tot_Rept_Positions_Long_All] [float] NULL,
	[Tot_Rept_Positions_Short_All] [float] NULL,
	[NonRept_Positions_Long_All] [int] NULL,
	[NonRept_Positions_Short_All] [int] NULL,
	[Open_Interest_Old] [float] NULL,
	[Prod_Merc_Positions_Long_Old] [int] NULL,
	[Prod_Merc_Positions_Short_Old] [int] NULL,
	[Swap_Positions_Long_Old] [int] NULL,
	[Swap_Positions_Short_Old] [int] NULL,
	[Swap_Positions_Spread_Old] [int] NULL,
	[M_Money_Positions_Long_Old] [int] NULL,
	[M_Money_Positions_Short_Old] [int] NULL,
	[M_Money_Positions_Spread_Old] [int] NULL,
	[Other_Rept_Positions_Long_Old] [int] NULL,
	[Other_Rept_Positions_Short_Old] [int] NULL,
	[Other_Rept_Positions_Spread_Old] [int] NULL,
	[Tot_Rept_Positions_Long_Old] [float] NULL,
	[Tot_Rept_Positions_Short_Old] [float] NULL,
	[NonRept_Positions_Long_Old] [float] NULL,
	[NonRept_Positions_Short_Old] [float] NULL,
	[Open_Interest_Other] [float] NULL,
	[Prod_Merc_Positions_Long_Other] [float] NULL,
	[Prod_Merc_Positions_Short_Other] [float] NULL,
	[Swap_Positions_Long_Other] [float] NULL,
	[Swap_Positions_Short_Other] [float] NULL,
	[Swap_Positions_Spread_Other] [float] NULL,
	[M_Money_Positions_Long_Other] [float] NULL,
	[M_Money_Positions_Short_Other] [float] NULL,
	[M_Money_Positions_Spread_Other] [float] NULL,
	[Other_Rept_Positions_Long_Other] [float] NULL,
	[Other_Rept_Positions_Short_Other] [float] NULL,
	[Other_Rept_Positions_Spread_Other] [float] NULL,
	[Tot_Rept_Positions_Long_Other] [float] NULL,
	[Tot_Rept_Positions_Short_Other] [float] NULL,
	[NonRept_Positions_Long_Other] [float] NULL,
	[NonRept_Positions_Short_Other] [float] NULL,
	[Change_in_Open_Interest_All] [float] NULL,
	[Change_in_Prod_Merc_Long_All] [float] NULL,
	[Change_in_Prod_Merc_Short_All] [float] NULL,
	[Change_in_Swap_Long_All] [float] NULL,
	[Change_in_Swap_Short_All] [float] NULL,
	[Change_in_Swap_Spread_All] [float] NULL,
	[Change_in_M_Money_Long_All] [float] NULL,
	[Change_in_M_Money_Short_All] [float] NULL,
	[Change_in_M_Money_Spread_All] [float] NULL,
	[Change_in_Other_Rept_Long_All] [float] NULL,
	[Change_in_Other_Rept_Short_All] [float] NULL,
	[Change_in_Other_Rept_Spread_All] [float] NULL,
	[Change_in_Tot_Rept_Long_All] [float] NULL,
	[Change_in_Tot_Rept_Short_All] [float] NULL,
	[Change_in_NonRept_Long_All] [float] NULL,
	[Change_in_NonRept_Short_All] [float] NULL,
	[Pct_of_Open_Interest_All] [float] NULL,
	[Pct_of_OI_Prod_Merc_Long_All] [float] NULL,
	[Pct_of_OI_Prod_Merc_Short_All] [float] NULL,
	[Pct_of_OI_Swap_Long_All] [float] NULL,
	[Pct_of_OI_Swap_Short_All] [float] NULL,
	[Pct_of_OI_Swap_Spread_All] [float] NULL,
	[Pct_of_OI_M_Money_Long_All] [float] NULL,
	[Pct_of_OI_M_Money_Short_All] [float] NULL,
	[Pct_of_OI_M_Money_Spread_All] [float] NULL,
	[Pct_of_OI_Other_Rept_Long_All] [float] NULL,
	[Pct_of_OI_Other_Rept_Short_All] [float] NULL,
	[Pct_of_OI_Other_Rept_Spread_All] [float] NULL,
	[Pct_of_OI_Tot_Rept_Long_All] [float] NULL,
	[Pct_of_OI_Tot_Rept_Short_All] [float] NULL,
	[Pct_of_OI_NonRept_Long_All] [float] NULL,
	[Pct_of_OI_NonRept_Short_All] [float] NULL,
	[Pct_of_Open_Interest_Old] [float] NULL,
	[Pct_of_OI_Prod_Merc_Long_Old] [float] NULL,
	[Pct_of_OI_Prod_Merc_Short_Old] [float] NULL,
	[Pct_of_OI_Swap_Long_Old] [float] NULL,
	[Pct_of_OI_Swap_Short_Old] [float] NULL,
	[Pct_of_OI_Swap_Spread_Old] [float] NULL,
	[Pct_of_OI_M_Money_Long_Old] [float] NULL,
	[Pct_of_OI_M_Money_Short_Old] [float] NULL,
	[Pct_of_OI_M_Money_Spread_Old] [float] NULL,
	[Pct_of_OI_Other_Rept_Long_Old] [float] NULL,
	[Pct_of_OI_Other_Rept_Short_Old] [float] NULL,
	[Pct_of_OI_Other_Rept_Spread_Old] [float] NULL,
	[Pct_of_OI_Tot_Rept_Long_Old] [float] NULL,
	[Pct_of_OI_Tot_Rept_Short_Old] [float] NULL,
	[Pct_of_OI_NonRept_Long_Old] [float] NULL,
	[Pct_of_OI_NonRept_Short_Old] [float] NULL,
	[Pct_of_Open_Interest_Other] [float] NULL,
	[Pct_of_OI_Prod_Merc_Long_Other] [float] NULL,
	[Pct_of_OI_Prod_Merc_Short_Other] [float] NULL,
	[Pct_of_OI_Swap_Long_Other] [float] NULL,
	[Pct_of_OI_Swap_Short_Other] [float] NULL,
	[Pct_of_OI_Swap_Spread_Other] [float] NULL,
	[Pct_of_OI_M_Money_Long_Other] [float] NULL,
	[Pct_of_OI_M_Money_Short_Other] [float] NULL,
	[Pct_of_OI_M_Money_Spread_Other] [float] NULL,
	[Pct_of_OI_Other_Rept_Long_Other] [float] NULL,
	[Pct_of_OI_Other_Rept_Short_Other] [float] NULL,
	[Pct_of_OI_Other_Rept_Spread_Other] [float] NULL,
	[Pct_of_OI_Tot_Rept_Long_Other] [float] NULL,
	[Pct_of_OI_Tot_Rept_Short_Other] [float] NULL,
	[Pct_of_OI_NonRept_Long_Other] [float] NULL,
	[Pct_of_OI_NonRept_Short_Other] [float] NULL,
	[Traders_Tot_All] [int] NULL,
	[Traders_Prod_Merc_Long_All] [int] NULL,
	[Traders_Prod_Merc_Short_All] [int] NULL,
	[Traders_Swap_Long_All] [int] NULL,
	[Traders_Swap_Short_All] [int] NULL,
	[Traders_Swap_Spread_All] [int] NULL,
	[Traders_M_Money_Long_All] [int] NULL,
	[Traders_M_Money_Short_All] [int] NULL,
	[Traders_M_Money_Spread_All] [int] NULL,
	[Traders_Other_Rept_Long_All] [int] NULL,
	[Traders_Other_Rept_Short_All] [int] NULL,
	[Traders_Other_Rept_Spread_All] [int] NULL,
	[Traders_Tot_Rept_Long_All] [float] NULL,
	[Traders_Tot_Rept_Short_All] [float] NULL,
	[Traders_Tot_Old] [int] NULL,
	[Traders_Prod_Merc_Long_Old] [int] NULL,
	[Traders_Prod_Merc_Short_Old] [int] NULL,
	[Traders_Swap_Long_Old] [int] NULL,
	[Traders_Swap_Short_Old] [int] NULL,
	[Traders_Swap_Spread_Old] [int] NULL,
	[Traders_M_Money_Long_Old] [int] NULL,
	[Traders_M_Money_Short_Old] [int] NULL,
	[Traders_M_Money_Spread_Old] [int] NULL,
	[Traders_Other_Rept_Long_Old] [int] NULL,
	[Traders_Other_Rept_Short_Old] [int] NULL,
	[Traders_Other_Rept_Spread_Old] [int] NULL,
	[Traders_Tot_Rept_Long_Old] [float] NULL,
	[Traders_Tot_Rept_Short_Old] [float] NULL,
	[Traders_Tot_Other] [float] NULL,
	[Traders_Prod_Merc_Long_Other] [float] NULL,
	[Traders_Prod_Merc_Short_Other] [float] NULL,
	[Traders_Swap_Long_Other] [float] NULL,
	[Traders_Swap_Short_Other] [float] NULL,
	[Traders_Swap_Spread_Other] [float] NULL,
	[Traders_M_Money_Long_Other] [float] NULL,
	[Traders_M_Money_Short_Other] [float] NULL,
	[Traders_M_Money_Spread_Other] [float] NULL,
	[Traders_Other_Rept_Long_Other] [float] NULL,
	[Traders_Other_Rept_Short_Other] [float] NULL,
	[Traders_Other_Rept_Spread_Other] [float] NULL,
	[Traders_Tot_Rept_Long_Other] [float] NULL,
	[Traders_Tot_Rept_Short_Other] [float] NULL,
	[Conc_Gross_LE_4_TDR_Long_All] [float] NULL,
	[Conc_Gross_LE_4_TDR_Short_All] [float] NULL,
	[Conc_Gross_LE_8_TDR_Long_All] [float] NULL,
	[Conc_Gross_LE_8_TDR_Short_All] [float] NULL,
	[Conc_Net_LE_4_TDR_Long_All] [float] NULL,
	[Conc_Net_LE_4_TDR_Short_All] [float] NULL,
	[Conc_Net_LE_8_TDR_Long_All] [float] NULL,
	[Conc_Net_LE_8_TDR_Short_All] [float] NULL,
	[Conc_Gross_LE_4_TDR_Long_Old] [float] NULL,
	[Conc_Gross_LE_4_TDR_Short_Old] [float] NULL,
	[Conc_Gross_LE_8_TDR_Long_Old] [float] NULL,
	[Conc_Gross_LE_8_TDR_Short_Old] [float] NULL,
	[Conc_Net_LE_4_TDR_Long_Old] [float] NULL,
	[Conc_Net_LE_4_TDR_Short_Old] [float] NULL,
	[Conc_Net_LE_8_TDR_Long_Old] [float] NULL,
	[Conc_Net_LE_8_TDR_Short_Old] [float] NULL,
	[Conc_Gross_LE_4_TDR_Long_Other] [float] NULL,
	[Conc_Gross_LE_4_TDR_Short_Other] [float] NULL,
	[Conc_Gross_LE_8_TDR_Long_Other] [float] NULL,
	[Conc_Gross_LE_8_TDR_Short_Other] [float] NULL,
	[Conc_Net_LE_4_TDR_Long_Other] [float] NULL,
	[Conc_Net_LE_4_TDR_Short_Other] [float] NULL,
	[Conc_Net_LE_8_TDR_Long_Other] [float] NULL,
	[Conc_Net_LE_8_TDR_Short_Other] [float] NULL,
	[Contract_Units] [varchar](200) NULL,
	[CFTC_Contract_Market_Code_Quotes] [varchar](6) NULL,
	[CFTC_Market_Code_Quotes] [varchar](4) NULL,
	[CFTC_Commodity_Code_Quotes] [float] NULL,
	[CFTC_SubGroup_Code] [varchar](3) NULL,
	[FutOnly_or_Combined] [varchar](8) NOT NULL,
	[provider][varchar](30) NOT NULL,
	[source] [varchar](30) NULL,
	[Week_of_Release] [datetime] NOT NULL,
	[date_created] [datetime] NULL,
	[date_modified] [datetime] NULL
) ON [PRIMARY]
GO

CREATE CLUSTERED COLUMNSTORE INDEX cci_futures_options_data ON [main].[futures_options_data];
GO

CREATE UNIQUE INDEX UI_FOD ON [main].[futures_options_data] ([provider], [Week_of_Release], [CFTC_Contract_Market_Code],
                   [CFTC_Market_Code], [CFTC_Region_Code], [CFTC_Commodity_Code], [FutOnly_or_Combined]);
GO
